steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'enable-apis'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud services enable \
          firebasestorage.googleapis.com \
          cloudfunctions.googleapis.com \
          cloudbuild.googleapis.com \
          artifactregistry.googleapis.com \
          run.googleapis.com \
          eventarc.googleapis.com \
          pubsub.googleapis.com \
          storage.googleapis.com \
          translate.googleapis.com \
          cloudbilling.googleapis.com \
          --project=$PROJECT_ID
  - name: 'node:22'
    id: 'install-deps'
    entrypoint: npm
    args: [ 'install' ]
  - name: 'node:22'
    id: 'install-functions-deps'
    entrypoint: npm
    args: [ '--prefix', 'functions', 'install', '--platform=linuxmusl' ]
  - name: ghcr.io/lessify/firebase:edge
    id: 'Pull Firebase Apps SDK Config'
    args: [ 'apps:sdkconfig', '--project=$PROJECT_ID', 'web', '--out=src/environments/firebase-config-tmp.json' ]
  - name: 'node:22'
    id: 'Copy Firebase Apps SDK Config'
    args: [ 'mv', '-f', 'src/environments/firebase-config-tmp.json', 'src/environments/firebase-config.json' ]
  - name: 'node:22'
    id: 'build-prod'
    entrypoint: npm
    args:
      - 'run'
      - 'build:prod'
    env:
      - 'LOCALESS_AUTH_CUSTOM_DOMAIN=${_LOCALESS_AUTH_CUSTOM_DOMAIN}'
      - 'LOCALESS_AUTH_PROVIDERS=${_LOCALESS_AUTH_PROVIDERS}'
      - 'LOCALESS_LOGIN_MESSAGE=${_LOCALESS_LOGIN_MESSAGE}'
      - 'LOCALESS_UNSPLASH_ENABLE=${_LOCALESS_UNSPLASH_ENABLE}'
  # deploy to firebase
  - name: ghcr.io/lessify/firebase:edge
    id: 'firebase-deploy'
    args: [ 'deploy', '--project=$PROJECT_ID', '--only=hosting,functions,storage,firestore', '--force' ]
options:
  logging: CLOUD_LOGGING_ONLY
