import { mkdtemp, rm } from 'node:fs/promises';
import { createWriteStream } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pipeline } from 'node:stream/promises';
import { Inject, Injectable, Logger } from '@nestjs/common';
import { and, eq } from 'drizzle-orm';
import type { FastifyReply, FastifyRequest } from 'fastify';
import ffmpeg from 'fluent-ffmpeg';
import sharp, { type Sharp } from 'sharp';
import { APP_CONFIG, type AppConfig } from '../../infra/config/config.js';
import { DATABASE, type Database } from '../../infra/database/database.module.js';
import { assets } from '../../infra/database/schema.js';
import { STORAGE_DRIVER, type StorageDriver } from '../../infra/storage/storage.driver.js';
import {
  CACHE_ASSET_MAX_AGE,
  CACHE_ASSET_NOT_FOUND_MAX_AGE,
  CACHE_BAD_REQUEST_MAX_AGE,
  publicCache,
} from '../../infra/http/v1/cache-control.js';
import { assetResponsePolicy } from './asset-headers.js';
import { buildAssetETag } from './asset-etag.js';
import { buildAssetQuery, findTransformParam } from './asset-query.js';
import { buildContentDisposition } from '../../infra/http/content-disposition.js';
import {
  applySharpTransforms,
  canonicalTransformSize,
  decodedAnimationPixels,
  isAnimatedPages,
  MAX_ANIMATED_PIXELS,
  parseAssetTransformQuery,
  resolveOutputFormat,
  sourceEncoderFormat,
} from './image-transform.js';
import { sendV1Error } from '../../infra/http/v1/v1-response.js';

type AssetRow = typeof assets.$inferSelect;

const FORMAT_MIME: Record<string, string> = { webp: 'image/webp', jpeg: 'image/jpeg', png: 'image/png', avif: 'image/avif' };
const FORMAT_EXT: Record<string, string> = { webp: '.webp', jpeg: '.jpg', png: '.png', avif: '.avif' };

export const originalKey = (spaceId: string, assetId: string) => `spaces/${spaceId}/assets/${assetId}/original`;
/** Generated bytes are cached next to the original and deleted with it. Keyed by what defines the bytes. */
export const renditionKey = (spaceId: string, assetId: string, etagSuffix: string, thumbnail: boolean) =>
  `spaces/${spaceId}/assets/${assetId}/renditions/${etagSuffix || 'orig'}${thumbnail ? '-thumbnail' : ''}`;

/** First frame of a video at `time`, as a file in `dir`. */
function extractVideoFrame(videoPath: string, dir: string, time = '00:00:01'): Promise<string> {
  const filename = 'frame.webp';
  return new Promise((resolve, reject) => {
    ffmpeg(videoPath)
      .on('end', () => resolve(join(dir, filename)))
      .on('error', (error: Error) => reject(new Error(`FFmpeg Error: ${error.message}`)))
      .screenshots({ timestamps: [time], filename, folder: dir });
  });
}

/**
 * The three public asset routes (`/assets/:id`, `/original`, `/download`), ported from
 * functions/src/v1/cdn.ts. Every branch keeps its documented behaviour; what changed is the I/O:
 * rows instead of Firestore docs, `StorageDriver` instead of the bucket, a rendition cache instead
 * of relying on the Firebase CDN, streamed passthroughs with Range support, and per-request temp
 * directories (the fixed `/tmp/assets-{id}` names could collide between concurrent requests).
 */
@Injectable()
export class AssetDeliveryService {
  private readonly logger = new Logger(AssetDeliveryService.name);

  constructor(
    @Inject(DATABASE) private readonly db: Database,
    @Inject(STORAGE_DRIVER) private readonly storage: StorageDriver,
    @Inject(APP_CONFIG) config: AppConfig,
  ) {
    if (config.ffmpegPath) ffmpeg.setFfmpegPath(config.ffmpegPath);
  }

  private async findAsset(spaceId: string, assetId: string): Promise<AssetRow | undefined> {
    const [row] = await this.db
      .select()
      .from(assets)
      .where(and(eq(assets.spaceId, spaceId), eq(assets.id, assetId)));
    return row;
  }

  /**
   * Two different failures, cached differently: no row means the asset doesn't exist (cache hard);
   * a row without its file is an upload in flight (never cache — it's about to appear).
   */
  private sendMissing(reply: FastifyReply, rowExists: boolean): void {
    if (rowExists) {
      sendV1Error(reply, 404, 'not-found', 'Not found, upload may still be in progress.', { cacheControl: 'no-cache' });
    } else {
      sendV1Error(reply, 404, 'not-found', 'Not found.', { cacheControl: publicCache(CACHE_ASSET_NOT_FOUND_MAX_AGE) });
    }
  }

  private sendBadRequest(reply: FastifyReply, message: string): void {
    sendV1Error(reply, 400, 'invalid-argument', message, { cacheControl: publicCache(CACHE_BAD_REQUEST_MAX_AGE) });
  }

  /** Streams a stored object, honouring a single `Range` (videos are where clients resume). */
  private sendObject(request: FastifyRequest, reply: FastifyReply, key: string, size: number): void {
    void reply.header('accept-ranges', 'bytes');
    const match = /^bytes=(\d*)-(\d*)$/.exec(request.headers.range ?? '');
    if (match && (match[1] || match[2])) {
      let start = match[1] ? Number(match[1]) : size - Number(match[2]);
      let end = match[1] && match[2] ? Number(match[2]) : size - 1;
      start = Math.max(0, start);
      end = Math.min(end, size - 1);
      if (start > end || start >= size) {
        void reply.code(416).header('content-range', `bytes */${size}`).send();
        return;
      }
      void reply
        .code(206)
        .header('content-range', `bytes ${start}-${end}/${size}`)
        .header('content-length', end - start + 1)
        .send(this.storage.createReadStream(key, { start, end }));
      return;
    }
    void reply.header('content-length', size).send(this.storage.createReadStream(key));
  }

  /** `GET /assets/:id/original` and `/download`: the stored bytes, untouched. */
  async serveStored(request: FastifyRequest, reply: FastifyReply, spaceId: string, assetId: string, attachment: boolean): Promise<void> {
    // No transform here, so a transform parameter is a caller error rather than something to ignore.
    const offending = findTransformParam(request.query as Record<string, unknown>);
    if (offending !== undefined) {
      this.sendBadRequest(
        reply,
        `Unsupported '${offending}' parameter on this route. It serves the stored bytes and applies no transform. ` +
          'Use GET /api/v1/spaces/{spaceId}/assets/{assetId} for transforms.',
      );
      return;
    }
    const key = originalKey(spaceId, assetId);
    const [object, asset] = await Promise.all([this.storage.stat(key), this.findAsset(spaceId, assetId)]);
    if (!object || !asset) {
      this.sendMissing(reply, asset !== undefined);
      return;
    }
    // `orig` is reserved for the stored bytes, keeping this tag distinct from every rendition's.
    if (asset.md5) {
      const etag = buildAssetETag(asset.md5, '', false);
      void reply.header('etag', etag);
      if (request.headers['if-none-match'] === etag) {
        void reply.code(304).header('cache-control', publicCache(CACHE_ASSET_MAX_AGE)).send();
        return;
      }
    }
    const policy = assetResponsePolicy(asset.type ?? undefined, attachment);
    void reply
      .header('cache-control', publicCache(CACHE_ASSET_MAX_AGE))
      .header('content-disposition', buildContentDisposition(`${asset.name}${asset.extension ?? ''}`, policy.attachment))
      .headers(policy.headers)
      .type(policy.contentType);
    this.sendObject(request, reply, key, object.size);
  }

  /** `GET /assets/:id`: transforms (`w`, `h`, `f`, `q`, `fit`, `thumbnail`) and quality normalisation. */
  async serveTransformed(request: FastifyRequest, reply: FastifyReply, spaceId: string, assetId: string): Promise<void> {
    const parsed = parseAssetTransformQuery(request.query as Record<string, unknown>);
    if (!parsed.ok) {
      // Cached: the rejection is a pure function of the query.
      this.sendBadRequest(reply, parsed.error.message);
      return;
    }
    const { quality, fit, thumbnail } = parsed.query;
    const key = originalKey(spaceId, assetId);
    const [object, asset] = await Promise.all([this.storage.stat(key), this.findAsset(spaceId, assetId)]);
    if (!object || !asset) {
      this.sendMissing(reply, asset !== undefined);
      return;
    }
    const assetType = asset.type ?? '';
    const extension = asset.extension ?? '';
    const metadata = (asset.metadata ?? undefined) as { width?: number; height?: number; pages?: number } | undefined;

    // Oversized requests redirect to the size the source can produce: one URL, one response.
    const canonical = canonicalTransformSize(parsed.query, { width: metadata?.width, height: metadata?.height });
    if (canonical.width !== parsed.query.width || canonical.height !== parsed.query.height) {
      const target = `/api/v1/spaces/${spaceId}/assets/${assetId}${buildAssetQuery({ ...parsed.query, ...canonical })}`;
      void reply.header('cache-control', publicCache(CACHE_ASSET_MAX_AGE)).redirect(target, 302);
      return;
    }
    const { width, height } = canonical;
    const format = resolveOutputFormat({
      requested: parsed.query.format,
      sourceType: assetType,
      quality,
      resizing: width !== undefined || height !== undefined,
    });
    // What the pipeline encodes to; `format` alone decides the response's type and extension.
    const encodeAs = format ?? sourceEncoderFormat(assetType);
    const outputType: string | undefined = format ? FORMAT_MIME[format] : undefined;
    const outputExt: string = format ? FORMAT_EXT[format] : extension;
    let filename = `${asset.name}${extension}`;
    // Names what the caller asked for (download filename).
    const suffix = [width ? `w${width}` : '', height ? `h${height}` : '', format ? `f${format}` : '', fit ? `fit${fit}` : '']
      .filter(Boolean)
      .join('-');
    // Describes the bytes: the effective encode, so equal outputs share a tag and different ones never do.
    const etagSuffix = [
      width ? `w${width}` : '',
      height ? `h${height}` : '',
      quality !== undefined ? `q${quality}` : '',
      encodeAs ? `f${encodeAs}` : '',
      fit ? `fit${fit}` : '',
    ]
      .filter(Boolean)
      .join('-');

    // Answered before any read or transform: revalidation costs a row lookup, not a re-encode.
    if (asset.md5) {
      const etag = buildAssetETag(asset.md5, etagSuffix, thumbnail);
      void reply.header('etag', etag);
      if (request.headers['if-none-match'] === etag) {
        void reply.code(304).header('cache-control', publicCache(CACHE_ASSET_MAX_AGE)).send();
        return;
      }
    }

    const explicitTransform = width !== undefined || height !== undefined || format !== undefined || thumbnail;
    // Still rasters we can encode are normalised to the encoder's default quality even without parameters.
    const normalisable = sourceEncoderFormat(assetType) !== undefined;

    // Reject an oversized animation from stored metadata before paying for the read. Thumbnails decode one frame.
    if (explicitTransform && !thumbnail && metadata && metadata.pages !== undefined) {
      const storedPixels = decodedAnimationPixels(metadata.width, metadata.height, metadata.pages);
      if (storedPixels > MAX_ANIMATED_PIXELS) {
        this.sendBadRequest(
          reply,
          `Animation is too large to transform: ${metadata.width}x${metadata.height} over ` +
            `${metadata.pages} frames is ${storedPixels} pixels, above the ${MAX_ANIMATED_PIXELS} limit. ` +
            "Request '?thumbnail' for a still frame.",
        );
        return;
      }
    }

    const cacheKey = renditionKey(spaceId, assetId, etagSuffix, thumbnail);
    let output: Buffer | undefined;
    let overwriteType: string | undefined;
    // True when `output` was generated (and so belongs in the rendition cache).
    let generated = false;
    /** The cached rendition, or `source()` transformed (only then is the original read). */
    const transform = async (source: () => Sharp | Promise<Sharp>): Promise<Buffer> => {
      if (await this.storage.stat(cacheKey)) return this.storage.read(cacheKey);
      generated = true;
      return applySharpTransforms(await source(), { width, height, quality, format: encodeAs, fit }).toBuffer();
    };

    if (assetType.startsWith('image/') && (explicitTransform || normalisable)) {
      if (assetType === 'image/webp' || assetType === 'image/gif') {
        // Possibly animated.
        const file = await this.storage.read(key);
        const probe = await sharp(file).metadata();
        const isAnimated = isAnimatedPages(probe.pages);
        if (thumbnail) {
          // An explicit request for a still: collapse to the first frame whatever the source.
          filename = `${asset.name}-${suffix ? `${suffix}-thumbnail` : 'thumbnail'}${outputExt}`;
          output = await transform(() => sharp(file, { page: 0, pages: 1, autoOrient: true }));
          overwriteType = outputType;
        } else if (isAnimated && !explicitTransform) {
          // A bare URL on an animation serves the stored bytes: re-encoding every frame is the most
          // expensive thing this endpoint does, and the pixel budget would make a plain <img> fail.
          output = file;
        } else if (isAnimated) {
          // Resizing decodes every frame at once, so the budget covers the whole animation.
          const frameHeight = probe.pageHeight ?? probe.height ?? 0;
          const decodedPixels = decodedAnimationPixels(probe.width, frameHeight, probe.pages);
          if (decodedPixels > MAX_ANIMATED_PIXELS) {
            this.sendBadRequest(
              reply,
              `Animation is too large to transform: ${probe.width}x${frameHeight} over ${probe.pages} frames is ` +
                `${decodedPixels} pixels, above the ${MAX_ANIMATED_PIXELS} limit. Request '?thumbnail' for a still frame.`,
            );
            return;
          }
          if (suffix) filename = `${asset.name}-${suffix}${outputExt}`;
          output = await transform(() => sharp(file, { animated: true, autoOrient: true }));
          overwriteType = outputType;
        } else {
          if (suffix) filename = `${asset.name}-${suffix}${outputExt}`;
          output = await transform(() => sharp(file, { autoOrient: true }));
          overwriteType = outputType;
        }
      } else if (assetType === 'image/svg+xml') {
        // No raster encoder for SVG: served as stored.
      } else {
        // Other images (jpeg, png, tiff, avif, …).
        if (suffix) filename = `${asset.name}-${suffix}${outputExt}`;
        output = await transform(async () => sharp(await this.storage.read(key), { autoOrient: true }));
        overwriteType = outputType;
      }
    } else if (assetType.startsWith('video/') && width !== undefined && thumbnail) {
      overwriteType = format ? FORMAT_MIME[format] : 'image/webp';
      filename = `${asset.name}-${suffix || `w${width}`}-thumbnail${format ? FORMAT_EXT[format] : '.webp'}`;
      if (await this.storage.stat(cacheKey)) {
        output = await this.storage.read(cacheKey);
      } else {
        output = await this.videoThumbnail(key, { width, height, quality, format: encodeAs, fit });
        generated = true;
      }
    }

    if (output && generated) {
      // Best effort: a failed cache write must not fail the response.
      await this.storage.put(cacheKey, output).catch(error => this.logger.warn(`Rendition cache write failed for ${cacheKey}: ${error}`));
    }

    const policy = assetResponsePolicy(overwriteType || assetType, false);
    void reply
      .header('cache-control', publicCache(CACHE_ASSET_MAX_AGE))
      .header('content-disposition', buildContentDisposition(filename, policy.attachment))
      .headers(policy.headers)
      .type(policy.contentType);
    if (output) {
      void reply.send(output);
    } else {
      this.sendObject(request, reply, key, object.size);
    }
  }

  private async videoThumbnail(key: string, options: Parameters<typeof applySharpTransforms>[1]): Promise<Buffer> {
    const dir = await mkdtemp(join(tmpdir(), 'localess-video-'));
    try {
      const videoPath = join(dir, 'source');
      await pipeline(this.storage.createReadStream(key), createWriteStream(videoPath));
      const frame = await extractVideoFrame(videoPath, dir);
      return await applySharpTransforms(sharp(frame, { autoOrient: true }), options).toBuffer();
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  }
}
