export interface UserInvite {
  displayName?: string
  email: string
  password: string
  role?: string
  permissions?: string[]
}

export enum UserPermission {
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  SPACE_MANAGEMENT = 'SPACE_MANAGEMENT',
  TRANSLATION_READ = 'TRANSLATION_READ',
  TRANSLATION_UPDATE = 'TRANSLATION_UPDATE',
  TRANSLATION_CREATE = 'TRANSLATION_CREATE',
  TRANSLATION_DELETE = 'TRANSLATION_DELETE',
  TRANSLATION_PUBLISH = 'TRANSLATION_PUBLISH',
  TRANSLATION_EXPORT = 'TRANSLATION_EXPORT',
  TRANSLATION_IMPORT = 'TRANSLATION_IMPORT',
  SCHEMATIC_READ = 'SCHEMATIC_READ',
  SCHEMATIC_UPDATE = 'SCHEMATIC_UPDATE',
  SCHEMATIC_CREATE = 'SCHEMATIC_CREATE',
  SCHEMATIC_DELETE = 'SCHEMATIC_DELETE',
  CONTENT_READ = 'CONTENT_READ',
  CONTENT_UPDATE = 'CONTENT_UPDATE',
  CONTENT_CREATE = 'CONTENT_CREATE',
  CONTENT_DELETE = 'CONTENT_DELETE',
  CONTENT_PUBLISH = 'CONTENT_PUBLISH'
}
