export const env = {
  "LOCALESS_FIREBASE_PROJECT_ID": "",
  "LOCALESS_FIREBASE_APP_ID": "",
  "LOCALESS_FIREBASE_STORAGE_BUCKET": "",
  "LOCALESS_FIREBASE_API_KEY": "",
  "LOCALESS_FIREBASE_AUTH_DOMAIN": "",
  "LOCALESS_FIREBASE_MESSAGING_SENDER_ID": "",
  "LOCALESS_AUTH_CUSTOM_DOMAIN": "",
  "LOCALESS_AUTH_PROVIDERS": "",
  "LOCALESS_UI_TOOLBAR_COLOR": "primary",
};
