import { z } from 'zod';

/** Path ids that end up in storage keys (assets, tasks) or are generated by `newId()`. */
export const zId = z.string().regex(/^[A-Za-z0-9_-]{1,128}$/);
export const zLocale = z.object({ id: z.string().min(1).max(64), name: z.string().min(1).max(200) });
export const zLabels = z.array(z.string().max(200)).max(100);
