/**
 * The per-project deployment config store.
 *
 * One `.env.<project-id>` file per Firebase project, gitignored, holding only the
 * decisions that cannot be read back from the live project. Everything else — the web SDK
 * config, the Firestore location, the Storage bucket — is fetched at deploy time.
 *
 * Keys are `LOCALESS_`-prefixed because `@lessify/angular-tools:set-env` (wired as
 * `prebuild:prod`) copies every matching `process.env` key into `src/environments/env.ts`.
 * That is the entire bridge from this file to the Angular bundle.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** Fallback wherever the region is read. Must match `functions/src/index.ts`. */
export const DEFAULT_REGION = 'europe-west6';

const PREFIX = '.env.';

/** Parses `KEY=value` lines. Comments (`#`) and blank lines are ignored. */
export function parseEnvFile(text) {
  const record = {};
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#')) continue;
    const separator = trimmed.indexOf('=');
    if (separator === -1) continue;
    const key = trimmed.slice(0, separator).trim();
    // Only the FIRST `=` separates; the rest belongs to the value.
    const raw = trimmed.slice(separator + 1).trim();
    record[key] = raw.replace(/^(["'])(.*)\1$/, '$2');
  }
  return record;
}

/** Inverse of `parseEnvFile`. Keys are sorted so diffs stay stable across writes. */
export function serializeEnvFile(record) {
  return Object.keys(record)
    .sort()
    .map(key => {
      const value = record[key] ?? '';
      return /[\s"']/.test(value) ? `${key}="${value}"` : `${key}=${value}`;
    })
    .join('\n');
}

export function configPath(root, projectId) {
  return join(root, `${PREFIX}${projectId}`);
}

/** Project ids that have a config file. A bare `.env` is not a project. */
export function listProjectConfigs(root) {
  return readdirSync(root)
    .filter(name => name.startsWith(PREFIX) && name.length > PREFIX.length)
    .map(name => name.slice(PREFIX.length))
    .sort();
}

export function readProjectConfig(root, projectId) {
  const path = configPath(root, projectId);
  let text;
  try {
    text = readFileSync(path, 'utf8');
  } catch {
    throw new Error(`No config found at ${PREFIX}${projectId}. Run: npm run localess:setup -- --project ${projectId}`);
  }
  return parseEnvFile(text);
}

export function writeProjectConfig(root, projectId, record) {
  const header = [
    `# Localess deployment config for ${projectId}`,
    '# Generated by `npm run localess:setup`. Gitignored - safe to edit by hand.',
    '# Only decisions live here; the Firebase SDK config is fetched at deploy time.',
    '',
  ].join('\n');
  writeFileSync(configPath(root, projectId), `${header}${serializeEnvFile(record)}\n`);
}

/**
 * `--project` wins, then a single config file. Ambiguity is an error rather than a guess:
 * Stage 1 has no prompt library, and picking a project to deploy to is not guessable.
 */
export function resolveProjectId(root, { flag } = {}) {
  if (flag) return flag;

  const candidates = listProjectConfigs(root);
  if (candidates.length === 1) return candidates[0];

  if (candidates.length === 0) {
    throw new Error('No .env.<project-id> config found. Run: npm run localess:setup');
  }
  throw new Error(`Several projects configured (${candidates.join(', ')}). Pass --project <id>.`);
}

/** The configured region, or the fallback. Never throws - an absent region is legal. */
export function requireRegion(record) {
  const region = record.LOCALESS_REGION;
  return region && region.trim() !== '' ? region.trim() : DEFAULT_REGION;
}
