---

name: Build and Push Docker Image

on:
  # Allows you to run workflow manually from Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Docker Tag'
        required: true
        default: 'latest'
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
    # Only build when files in these directories have been changed
    paths:
      - src/**
      - functions/**
      - angular.json
      - Dockerfile
      - firebase.json
      - firestore.indexes.json
      - firestore.rules
      - package.json
      - storage.rules

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/localess
          tags: |
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          platforms: linux/amd64
          push: true
